config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  get 'welcome/index'
  devise_for :users
  resources :users do
    resources  :items, only: [:create, :destroy]
  end


end

app/models/item.rb
class Item < ActiveRecord::Base
  require 'action_view'
  include ActionView::Helpers::DateHelper
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    current_user.items << Item.create(name: params[:item][:name])
    redirect_to current_user
  end

  def destroy
    Item.find(params[:id]).delete
    redirect_to current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Blocitoff #{@user.name}"
      create_session(@user)
      redirect_to root path
    else
      flash.now[:alert] = "There was an error creating you account. Please try again."
      render :new
    end
  end

  def show
    @item = Item.new

    # render "/views/users/show.html.erb"
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item.html.erb
<li>
  <%= item.name %>
  <%#= distance_of_time_in_words %>

  <%= distance_of_time_in_words(item.created_at, Time.now) %>
  <%= link_to "", [current_user, item], method: :delete, class: 'glyphicon glyphicon-ok' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=devise-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>

      <div class="pull-right user-info">
      <% if current_user %>
        <div class="pull-right">
         <br/>
         <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
  </ul>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
Currently Logged In User:<%= current_user.email %>


<ul>
  <%= render current_user.items %>
</ul>


<%= form_for [current_user, @item] do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocitoff</h1>
  <p>Something about Blocitoff</p>
</div>